### ISSUE TITLE
Build for python 3.8 and 3.9

### ISSUE THREAD

**Issue by asfaltboy** [joerick/pyinstrument_cext#5]
If I'm not mistaken, it should be enough to bump the version and tag, and travis should use `cibuildwheel` to upload the latest (macos and manylinux) wheels to pypi. ~~I will try to build the wheels in my fork to test this out firstly~~ see PR #6 for my stab at this.

This will make our lives easier in the realm of slim container images 🙂

**Comment by joerick** [comment]
Okie doke, that's released now!
